@startuml
hide empty description
[*] --> 01_ENTER_DATA

01_ENTER_DATA: Neuer Antrag, Nutzer können Daten eingeben
01_ENTER_DATA -down-> 02_FINANCING_OFFER_PROVIDED: BORROWER_SUBMIT_DATA_01_02
01_ENTER_DATA --> 99_EXIT_TO_BANK : BORROWER_EXIT_TO_BANK_xx_99

02_FINANCING_OFFER_PROVIDED: Angebot ist fertig, Nutzer können dieses annehmen.\nNutzer können Dokumente hochladen\n und Informationen zur Abwicklung eingeben.
02_FINANCING_OFFER_PROVIDED -down-> 03_FINANCING_OFFER_SUBMITTED : BORROWER_SUBMIT_FINANCING_OFFER_02_03
02_FINANCING_OFFER_PROVIDED --> 99_EXIT_TO_BANK : BORROWER_EXIT_TO_BANK_xx_99
02_FINANCING_OFFER_PROVIDED -[#blue]-> 01_ENTER_DATA : BACKOFFICE_REQUEST_DATA_CORRECTION_02_01

03_FINANCING_OFFER_SUBMITTED: Dokumente und Informationen zum Antrag vollständig.\nNutzer können Antrag einreichen\n – automatische Weiterleitung zu Identifizierung und Signatur
03_FINANCING_OFFER_SUBMITTED --> 99_EXIT_TO_BANK : BORROWER_EXIT_TO_BANK_xx_99
03_FINANCING_OFFER_SUBMITTED -down-> 04_1_IDENTIFICATION_IN_PROGRESS : BORROWER_START_IDENTIFICATION_03_04_1

04_1_IDENTIFICATION_IN_PROGRESS: Identifizierung oder Signatur sind (noch) nicht positiv abgeschlossen sind.\nNutzer bekommen Hilfe / Info dazu.
04_1_IDENTIFICATION_IN_PROGRESS --> 03_FINANCING_OFFER_SUBMITTED : BORROWER_FAILED_IDENTIFICATION_04_1_03
04_1_IDENTIFICATION_IN_PROGRESS --> 99_EXIT_TO_BANK : BORROWER_EXIT_TO_BANK_xx_99
04_1_IDENTIFICATION_IN_PROGRESS -down-> 04_2_IDENTIFICATION_IN_PROGRESS : BORROWER_SUCCESSFUL_IDENTIFICATION_04_1_04_2

04_2_IDENTIFICATION_IN_PROGRESS: Identifizierung oder Signatur des zweiten Kreditnehmers sind (noch) nicht positiv abgeschlossen sind.\nNutzer bekommen Hilfe / Info dazu.
04_2_IDENTIFICATION_IN_PROGRESS --> 04_1_IDENTIFICATION_IN_PROGRESS : SECOND_BORROWER_FAILED_IDENTIFICATION_04_2_04_1
04_2_IDENTIFICATION_IN_PROGRESS --> 99_EXIT_TO_BANK : BORROWER_EXIT_TO_BANK_xx_99
04_2_IDENTIFICATION_IN_PROGRESS -down-> 05_IN_AUDIT : SECOND_BORROWER_SUCCESSFUL_IDENTIFICATION_04_2_05

05_IN_AUDIT: Prüfung durch Backoffice. Nutzer warten.
05_IN_AUDIT -down[#blue]-> 06_1_AUDIT_RESULT_POSITIVE : BACKOFFICE_ACCEPT_AUDIT_05_06_1
05_IN_AUDIT -[#blue]-> 06_2_AUDIT_RESULT_NEGATIVE : BACKOFFICE_REJECT_AUDIT_05_06_2

06_1_AUDIT_RESULT_POSITIVE: Ergebnis positiv. Nutzer kann Urkunden abrufen und versenden lassen
06_1_AUDIT_RESULT_POSITIVE -[#blue]-> 07_DOCUMENTS_REQUESTED : BACKOFFICE_REQUEST_DOCUMENTS_06_1_07

06_2_AUDIT_RESULT_NEGATIVE: Ergebnis negativ: \nNutzer kann ggf. Kontakt per Chat aufnehmen\noder Kontakt zur Bank aufnehmen.
06_2_AUDIT_RESULT_NEGATIVE --> 99_EXIT_TO_BANK : BORROWER_EXIT_TO_BANK_xx_99
06_2_AUDIT_RESULT_NEGATIVE -[#blue]-> 99_EXIT_TO_BANK : BACKOFFICE_EXIT_TO_BANK_xx_99

07_DOCUMENTS_REQUESTED: Backoffice verschickt Unterlagen.\nKunde wartet.
07_DOCUMENTS_REQUESTED --> 08_DOCUMENTS_SENT_OUT : BORROWER_CREATE_AND_SEND_DOCUMENTS_07_08

08_DOCUMENTS_SENT_OUT: Unterlagen veschickt
08_DOCUMENTS_SENT_OUT --> [*]

99_EXIT_TO_BANK: 	Kunde hat Wunschgeäußert, \nProzess in einer Bankstelle weiterzuführen.
99_EXIT_TO_BANK --> [*]
@enduml
